bump github.com/containers/buildah to v1.16.0
Bump github.com/containers/buildah to the v1.16 release.

Move pins for k8s.io repositories that we're using from v1.19.0-rc.3 to
v1.19.0 proper.

This should address https://bugzilla.redhat.com/show_bug.cgi?id=1813258
and https://bugzilla.redhat.com/show_bug.cgi?id=1828119.

Signed-off-by: Nalin Dahyabhai <nalin@redhat.com>

diff --git a/vendor/github.com/containers/buildah/.cirrus.yml b/vendor/github.com/containers/buildah/.cirrus.yml
--- a/vendor/github.com/containers/buildah/.cirrus.yml
+++ b/vendor/github.com/containers/buildah/.cirrus.yml
@@ -27,11 +27,17 @@ env:
     ####
     # GCE project where images live
     IMAGE_PROJECT: "libpod-218412"
-    # TODO: Setting up from base-images is very inefficient, use libpod's cache-images instead?
-    FEDORA_CACHE_IMAGE_NAME: "fedora-cloud-base-30-1-2-1565360543"
-    PRIOR_FEDORA_CACHE_IMAGE_NAME: "fedora-cloud-base-29-1-2-1565360543"
-    UBUNTU_CACHE_IMAGE_NAME: "ubuntu-1904-disco-v20190724"
-    PRIOR_UBUNTU_CACHE_IMAGE_NAME: "ubuntu-1804-bionic-v20190722a"
+    # See https://github.com/containers/podman/blob/master/contrib/cirrus/README.md#test_build_cache_images_task-task
+    FEDORA_NAME: "fedora-32"
+    PRIOR_FEDORA_NAME: "fedora-31"
+    UBUNTU_NAME: "ubuntu-20"
+    PRIOR_UBUNTU_NAME: "ubuntu-19"
+
+    _BUILT_IMAGE_SUFFIX: "podman-6530021898584064"
+    FEDORA_CACHE_IMAGE_NAME: "${FEDORA_NAME}-${_BUILT_IMAGE_SUFFIX}"
+    PRIOR_FEDORA_CACHE_IMAGE_NAME: "${PRIOR_FEDORA_NAME}-${_BUILT_IMAGE_SUFFIX}"
+    UBUNTU_CACHE_IMAGE_NAME: "${UBUNTU_NAME}-${_BUILT_IMAGE_SUFFIX}"
+    PRIOR_UBUNTU_CACHE_IMAGE_NAME: "${PRIOR_UBUNTU_NAME}-${_BUILT_IMAGE_SUFFIX}"
 
     ####
     #### Command variables to help avoid duplication
@@ -106,15 +112,30 @@ gce_instance:
     # not supported by bors-ng
     # allow_failures: $CI == $CI
 
-    timeout_in: 30m
+    timeout_in: 45m
 
     setup_script: '${SCRIPT_BASE}/setup.sh |& ${_TIMESTAMP}'
     build_script: '${SCRIPT_BASE}/build.sh |& ${_TIMESTAMP}'
-    # FIXME: These tests mostly/always fail
-    unit_test_script: '${SCRIPT_BASE}/test.sh unit |& ${_TIMESTAMP} || true'
+    unit_test_script: '${SCRIPT_BASE}/test.sh unit |& ${_TIMESTAMP}'
 
     binary_artifacts:
         path: ./bin/*
+
+
+'cirrus-ci/only_prs/conformance_task':
+    gce_instance:  # Only need to specify differences from defaults (above)
+        image_name: "${UBUNTU_CACHE_IMAGE_NAME}"
+
+    # see bors.toml
+    skip: $CIRRUS_BRANCH =~ ".*\.tmp"
+
+    # don't fail the PR when we fail until #2480 is merged
+    allow_failures: true
+
+    timeout_in: 20m
+
+    setup_script: '${SCRIPT_BASE}/setup.sh |& ${_TIMESTAMP}'
+    conformance_test_script: '${SCRIPT_BASE}/test.sh conformance |& ${_TIMESTAMP}'
 
 
 # This task runs `make vendor` followed by ./hack/tree_status.sh to check
@@ -153,12 +174,9 @@ gce_instance:
         - 'cirrus-ci/only_prs/gate'
         - 'cirrus-ci/only_prs/vendor'
 
-    container:
-        image: registry.fedoraproject.org/fedora:30
-
     env:
         matrix:
-            CROSS_TARGET: darwin
+            CROSS_TARGET: bin/buildah.darwin
 
     setup_script: '${SCRIPT_BASE}/setup.sh |& ${_TIMESTAMP}'
     build_script: '${SCRIPT_BASE}/build.sh |& ${_TIMESTAMP}'
@@ -179,8 +197,7 @@ gce_instance:
     gce_instance:  # Only need to specify differences from defaults (above)
         matrix:  # Duplicate this task for each matrix product.
             image_name: "${FEDORA_CACHE_IMAGE_NAME}"
-            # TODO: Re-enable once prior image is F30 and above is F31
-            # image_name: "${PRIOR_FEDORA_CACHE_IMAGE_NAME}"
+            image_name: "${PRIOR_FEDORA_CACHE_IMAGE_NAME}"
             image_name: "${UBUNTU_CACHE_IMAGE_NAME}"
             image_name: "${PRIOR_UBUNTU_CACHE_IMAGE_NAME}"
 
@@ -247,8 +264,43 @@ gce_instance:
         CIRRUS_CLONE_DEPTH: 1  # no code is being used by this task
 
     container:
-        image: "registry.fedoraproject.org/fedora-minimal:latest"
+        image: "quay.io/libpod/fedora-minimal:latest"
         cpu: 1
         memory: 1
 
     script: /bin/true
+
+# Build the static binary
+'cirrus-ci/only_prs/static_binary_task':
+    depends_on:
+        - "cirrus-ci/only_prs/gate"
+
+    gce_instance:
+        image_name: "${FEDORA_CACHE_IMAGE_NAME}"
+        cpu: 8
+        memory: 12
+        disk: 200
+
+    init_script: |
+        set -ex
+        setenforce 0
+        growpart /dev/sda 1 || true
+        resize2fs /dev/sda1 || true
+        yum -y install podman
+
+    nix_cache:
+      folder: '.cache'
+      fingerprint_script: |
+        echo "nix-v1-$(sha1sum nix/nixpkgs.json | head -c 40)"
+
+    build_script: |
+        set -ex
+        mkdir -p .cache
+        mv .cache /nix
+        if [[ -z $(ls -A /nix) ]]; then podman run --rm --privileged -ti -v /:/mnt nixos/nix cp -rfT /nix /mnt/nix; fi
+        podman run --rm --privileged -ti -v /nix:/nix -v ${PWD}:${PWD} -w ${PWD} nixos/nix nix --print-build-logs --option cores 8 --option max-jobs 8 build --file nix/
+        mv /nix .cache
+        chown -Rf $(whoami) .cache
+
+    binaries_artifacts:
+        path: "result/bin/buildah"
